### ISSUE TITLE
send_fleet to debris fields

### ISSUE THREAD

**Issue by ghost** [alaingilbert/pyogame#11]
Sorry to bother you again.
I'm trying to automate recycling but it won't work.

```
from ogame.constants import Ships, Speed, Missions, Buildings, Research, Defense
ogame = OGame(uni, username, password) 

ships = [(Ships['Recycler'], 1)]
speed = Speed['100%']
where = {'galaxy': 1, 'system': 1, 'position': 1}
mission = Missions['RecycleDebrisField']
resources = {'metal': 0, 'crystal': 0, 'deuterium': 0}
ogame.send_fleet(PLANET_ID, ships, speed, where, mission, resources)
```

Unfortunately the code above won't send a fleet. Though there are no error messages either.
I have tried finding the issue and I guess it's the mission number, because sending a recycler on deploy or transport mission to another planet works just fine.

I also tried sending it to coordinates with existing debris fields and without, nothing happens unfortunately.
I noticed when you are in game you need to actively select the debris field AND the mission type when sending a fleet, so maybe that's where the problem is.

**Comment by alaingilbert** [comment]
You are right, we have to manually say we want the fleet to go to the `debris field` instead of the `planet`.
Here is a fix for the `Recycle` mission.
https://github.com/alaingilbert/pyogame/commit/514903e36793a4d996dc421dea15a02964f5f389

Your code should work without any changes. (with the latest version of pyogame)

**Comment by ghost** [comment]
Yep that works now, thanks.
