### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by dboz** [alaingilbert/pyogame#2]
From last updating of ogame, when try to perform the login I have the following response:

`self.ogame_session = soup.find('meta', {'name': 'ogame-session'}) \
AttributeError: 'NoneType' object has no attribute 'get'
`
the problem seems to be related on user agent not valid on the post request

**Comment by The1NdNly** [comment]
Ever get around this buddy?

**Comment by alaingilbert** [comment]
I made a little fix : https://github.com/alaingilbert/pyogame/commit/135633876c61b5af74cf33b2317e709d8874d785
Let me know if you still have any issues... It works for me now on the latests servers (Nusakan)

**Comment by The1NdNly** [comment]
I was just about to do a pull req. I'm expanding your framework now. you still play? I'm going to come back on the next server, going to make a bot for it from this. I have made one previously with c++ but its so much easer to use python :) 

Any idea if you can extract data from the galaxy view? i remember that was a major issue with curl and c++ due to JS processing.

I totally forgot about the new servers, ill have to check those out, just testing it on my vmode quantum account atm.

On a side note here is another bug fix.. more to get rid of those annoying errors. - heh aint got git set up atm, its just replace 15  "soup = BeautifulSoup(res)" to  "soup = BeautifulSoup(res, "lxml")" to stop those warnings. 
Best regards, the1

Edit: Whats the big change that would break this in Nusakan? i cant see  much of a difference in 6.0?

**Comment by alaingilbert** [comment]
Wow this is awesome.
I would be curious to see the c++ code for the bot ^^

I don't play much anymore. That's why I am unaware when something break.

Feel free to make any pull request :)

And, there is no change that break Nusakan...
I meant, I tried some basic code on the "Nusakan" universe and everything seems to work properly.

**Comment by The1NdNly** [comment]
Ah awesome! 
Well another reason Im here is Im on Linux and that was written on windows with VS and i have no idea how many library. ill see if i can find it for you on one of my old drives. 

Would you be interested in working on this again with me a little? i have some nice ideas - and it seems there is going to be a new server soon, x5 fleet and ecom. Acs too ;)

**Comment by alaingilbert** [comment]
That could be interesting.
We can create a shared "private repo" on bitbucket if you want,
to define some logic/tasks/goals...

**Comment by The1NdNly** [comment]
sounds like a plan to me. My name is the same over there, or do you need a email?
Edit: found you.
