### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by emmanuelbernieri** [alaingilbert/pyogame#33]
impossible to execute the connector: 
ogame = OGame('Uriel', USER, PASW)
always the same error -> BAD CREDENTIALS

**Comment by alaingilbert** [comment]
J'assume que tu parle français ?
Si c'est le cas, gâte toi :P

Otherwise, are you sure the `USER` and `PASW` values are set properly ?
let say you `print(USER, PASW)` can you see the right values ?

Also, the default domain is `en.ogame.gameforge.com`, so if you're playing on `fr.ogame.gameforge.com`, you have to do:

```py
ogame = OGame('Uriel', USER, PASW, domain='fr.ogame.gameforge.com')
```

**Comment by emmanuelbernieri** [comment]
perfect it's working the problem was with the domain. Thanks for all
