### ISSUE TITLE
The login page of ogame has changed

### ISSUE THREAD

**Issue by zunami3** [alaingilbert/pyogame#37]

**Comment by hugo-dlb** [comment]
I'm using a fork of pyogame and here's how I implemented the new login with the lobby:
https://pastebin.com/QEgBqMv5

Note that I am using new variables like `self.universe_id`.
Here's the code snippet of my constructor:
https://pastebin.com/0UYTSj8R

The get_universe_url method is also broken because the whole login page disappeared so we can no longer get the url from the select. What I'm doing is that it is you who supply the universe url in the constructor. Therefore my get_universe_url method is just the following:
https://pastebin.com/q88XWd8p

I am not handling errors at all. It's just so you have something working until a proper solution is proposed. Also there are some hard-coded variables like `fr` for the language...

**Comment by alaingilbert** [comment]
Thanks for letting me know. I'll see if I can fix it tomorrow.
Otherwise if someone wants to make a PR, I'll take it :)

**Comment by zunami3** [comment]
Thx :) That would be really great

**Comment by alaingilbert** [comment]
Alright, the new version (1.2.0) should work with the new login page.
Huge thanks to @turgodi for the code. It helped a lot :)
