### ISSUE TITLE
send_fleet issue

### ISSUE THREAD

**Issue by YOLOP0wn** [alaingilbert/pyogame#67]
send_fleet function returns me 'False" 

Do you know what's wrong ?

**Comment by YOLOP0wn** [comment]
Ok i've found, the issue was that my fleet cannot transport more resources  than it can.
So the best would be to have the possibility  to say to the send_fleet fonction, to take as much resources than it can.

**Comment by PiecePaperCode** [comment]
ogame server dosent accept invalid send fleet requests
You can solve your problem in 3 ways. 
- Create an resource function that calculates the needed space of resources you wanna send and compare it with your resources.
- Build more Transporters than you have resources for on your celestial 
- create an standart fleet whit exact known resources and just use it as a template

There was a time ogame accepted this and it would do it. but they now check if it makes sense now before the fulfill it

**Comment by YOLOP0wn** [comment]
yes i created a function that calculate resources depending on my fleet capacity, with deut prio 3, crystal prio 2 and metal 1, i did some test in think it works quite well

**Comment by PiecePaperCode** [comment]
this lib is quite "low level" it is basicly just giving you one to one functions that the ogame browser client also does. 
Because of its "low level" nature, programmers that create more complex things will need to do more work.

And they check before they send. There is a function in ogame where you can give it a fleet configuration and it will tell you if it is valid.
But send Fleet already does that.
